#!/bin/sh
echo 'GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT nvidia-drm.modeset=1"' > /etc/default/grub.d/uf-nvidia.cfg
echo 'options nvidia-drm modeset=1 
options nvidia NVreg_UsePageAttributeTable=1' > /etc/modprobe.d/nvidia.conf
/usr/sbin/update-grub
